#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHPANEL_HIMAX) += himax_common.o
obj-$(CONFIG_TOUCHPANEL_HIMAX_HX83112A_NOFLASH) += hx83112a_noflash/

#endif
